### ISSUE TITLE
.gitignore inside tarball

### ISSUE THREAD

**Issue by pirat89** [phracek/preupgrade-assistant#23]
.gitignore is inside tarball, but .git is not included. Probably this file shouldn't be part of tarball too. What do you think?

**Comment by misli** [comment]
.gitignore has been commited into the repo, therefore it appears inside the tarball.
Since there is no easy way to exclude files from tarball, which is being generated by tito, the only way I see is to remove it from the repo content and let everybody to keep his/her own copy of .gitignore file.
I'd rather keep it in the repo and therefore in the tarball.

**Comment by pirat89** [comment]
Well, in that case it's probably better keep it in tarball.
