### ISSUE TITLE
preupg-kickstart binary for kickstart generation

### ISSUE THREAD

**Issue by phracek** [phracek/preupgrade-assistant#90]
It would be really useful to provide a binary for kickstart generation instead of
~~~
preupg --kickstart
~~~

We have more chance to add a lot of options which would be useful for administrators.
like channels, subscriptions etc.

The binary should have a name like
~~~
preupg-kickstart-generator
~~~

Any comment is welcome

**Comment by pirat89** [comment]
Label *preupg-kickstart* seems better than *preupg-kickstart-generator* - I prefer shorter names of script. However the longer version is maybe more matching to other script names.

As was discussed earlier, '*preupg --kickstart*' should be still kept due to backward compatibility and just call the new script. And maybe it could suggest using of the new script in output, which will have more functionality.

**Comment by phracek** [comment]
Fixed by commit https://github.com/phracek/preupgrade-assistant/commit/e5e74d863ac488c765a5c02e6a3e21c153fb29b7
